import React, { createContext, useState, useContext } from 'react';


const translations = {
    en: {
        myClasses: "My Classes",
        type: "Type",
        lecture: "Lecture",
        seminar: "Seminar",
        project: "Project",
        lab: "Lab",
        number: "Number",
        absenceLimit: "Absence Limit",
        editAbsenceLimit: "Edit Max Absences",
        lastName: "Last Name",
        firstName: "First Name",
        absences: "Absences",
        present: "Present",
        late: "Late",
        absent: "Absent",
        excused: "Excused",
        none: "None",
        year: "Year",
        semester: "Semester",
        room: "Room",
        date: "Date",
        day: "Day",
        time: "Time",
        totalLateTime: "Total Late Time",
        timesLate: "Times Student was late",
        averageAttended: "Average Late Time over attended Classes",
        averageLate: "Average Late Time over late Classes",
        totalMissed: "Total Missed Classes",
        totalUnexcused: "Total Unexcused Absences",
        attendancePercentage: "Attendance Percentage",
        outOfMax1: "out of",
        outOfMax2: "allowed",
        status: "Status",
        save: "Save",
        cancel: "Cancel",
        close: "Close",
        accept: "Accept",
        reject: "Reject",
        upload: "Upload",
        login: "Login",
        logout: "Logout",
        noAccount: "Don't have an account?",
        register: "Register",
        alreadyLoggedIn: "You are already logged in.",
        inputUniEmail: "Put your university email address below to register.",
        changeLanguage: "polski",
        statistics: "Statistics",
        monday: "Monday",
        tuesday: "Tuesday",
        wednesday: "Wednesday",
        thursday: "Thursday",
        friday: "Friday",
        saturday: "Saturday",
        sunday: "Sunday",
        studentProfile: "Student Profile",
        changePassword: "Change password",
        teacherProfile: "Teacher Profile",
        notesToReview: "There is doctors notes to review",
        doctorsNotes: "Doctors Notes",
        doctorsNote: "Doctors Note",
        subject: "Subject",
        noFiles: "No files available",
        pleaseSelectFile: "Please select a file",
        fileUploaded: "File uploaded successfully",
        chooseDateWithRecord: "Please choose a date with an attendance record",
        uploadFailed: "Failed to upload file",
        uploadNote: "Upload Doctors Note",
        currentClass: "Current Class",
        haveAccount: "Already have an account?",
        notYet: "Future"
    },


    pl: {
        myClasses: "Moje Przedmioty",
        type: "Typ",
        lecture: "Wykład",
        seminar: "Seminarium",
        project: "Projekt",
        lab: "Zajęcia laboratoryjne",
        number: "Numer",
        absenceLimit: "Limit Nieobecności",
        editAbsenceLimit: "Edytuj Limit Nieobecności",
        lastName: "Nazwisko",
        firstName: "Imię",
        absences: "Nieobecności",
        present: "Obecny/a",
        late: "Spóźniony/a",
        absent: "Nieobecny/a",
        excused: "Usprawiedliwiony/a",
        none: "Brak",
        year: "Rok",
        semester: "Semestr",
        room: "Sala",
        date: "Data",
        day: "Dzień",
        time: "Czas",
        totalLateTime: "Suma Spóźnień",
        timesLate: "Liczba Spóźnień",
        averageAttended: "Średnie Spóźnienie na Obecności",
        averageLate: "Średnie Spóźnienie",
        totalMissed: "Suma Nieobecności",
        totalUnexcused: "Suma Nieusprawiedliwień",
        attendancePercentage: "Procent Obecności",
        outOfMax1: "z",
        outOfMax2: "dozwolonych",
        status: "Status",
        save: "Zapisz",
        cancel: "Anuluj",
        close: "Zamknij",
        accept: "Akceptuj",
        reject: "Odmów",
        upload: "Prześlij",
        login: "Zaloguj",
        logout: "Wyloguj",
        noAccount: "Nie masz konta?",
        register: "Zarejestruj",
        alreadyLoggedIn: "Jesteś już zalogowany/a.",
        inputUniEmail: "Podaj email uniwersytecki poniżej aby się zarejestrować.",
        changeLanguage: "english",
        statistics: "Statystyki",
        monday: "Poniedziałek",
        tuesday: "Wtorek",
        wednesday: "Środa",
        thursday: "Czwartek",
        friday: "Piątek",
        saturday: "Sobota",
        sunday: "Niedziela",
        studentProfile: "Profil Studenta",
        changePassword: "Zmień hasło",
        teacherProfile: "Profil Nauczyciela",
        notesToReview: "Zwolnienia lekarskie oczekują zatwierdzenia",
        doctorsNotes: "Zwolnienia lekarskie",
        doctorsNote: "Zwolnienie lekarskie",
        subject: "Przedmiot",
        noFiles: "Brak dostępnych plików",
        pleaseSelectFile: "Proszę wybrać plik",
        fileUploaded: "Plik przesłany pomyślnie",
        chooseDateWithRecord: "Proszę wybrać datę z listy obecności",
        uploadFailed: "Przesyłanie pliku nie powiodło się",
        uploadNote: "Prześlij zwolnienie lekarskie",
        currentClass: "Obecne zajęcia",
        haveAccount: "Masz juz konto?",
        notYet: "Zajęcia się jeszcze nie odbyły"

    },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('en');
    const t = (key) => translations[language][key];


    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
